spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false

